services:
  - type: web
    name: tiny-ando
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app.main:app
    healthCheckPath: /healthz
