services:
  - type: web
    name: tiny-ando
    branch: main
    autoDeploy: true
    env: python
    plan: free
    runtime: python
    buildCommand: ./scripts/render-build.sh
    startCommand: ./scripts/render-start.sh
    healthCheckPath: /healthz
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.14
      - key: MAX_INPUT_CHARS
        value: "1000"
